services:
  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_DB: keycloak-custom-theme
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - keycloak-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak-custom-theme"]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: cloakwise-io/keycloak-custom-theme:latest
    build:
      context: .
    container_name: keycloak
    command: ["--optimized", "--import-realm"]
    environment:
      # set hostname if you are behind a reverse proxy
      # KC_HOSTNAME: localhost
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak-custom-theme
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      # Set default values for admin user
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: adminpassword
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - keycloak-network
    volumes:
      - ./realms:/opt/keycloak/data/import

volumes:
  postgres_data:

networks:
  keycloak-network: {}
